import { test, expect } from '@playwright/test';

test.describe('HY-END Comprehensive User Flow', () => {
  const uniqueId = Date.now();
  const testEmail = `testuser_${uniqueId}@hyend.ac.kr`;
  const testPassword = 'Password123!';

  test('Sign Up, Login, and verify features', async ({ page }) => {
    // 1. Visit landing page
    await page.goto('/');
    await expect(page).toHaveTitle(/.+/);

    // Capture console errors
    const consoleErrors: string[] = [];
    page.on('console', msg => {
      if (msg.type() === 'error') {
        const text = msg.text();
        // Ignore styled-components transient prop warnings in React development mode
        if (
          text.includes('React does not recognize') ||
          text.includes('non-boolean attribute') ||
          text.includes('styled-components')
        ) {
          return;
        }
        consoleErrors.push(text);
        console.log(`BROWSER CONSOLE ERROR: ${text}`);
      }
    });

    // 2. Open Sign Up Modal
    const joinUsBtn = page.getByRole('button', { name: /Join Us/i });
    await expect(joinUsBtn).toBeVisible();
    await joinUsBtn.click();

    // Step 1: Email and Password
    await page.locator('input[type="email"]').fill(testEmail);
    await page.locator('input[type="password"]').fill(testPassword);
    await page.getByRole('button', { name: '다음' }).click();

    // Step 2: Details
    await page.locator('input[placeholder="이름"]').fill('테스트유저');
    await page.locator('input[placeholder="학부"]').fill('컴퓨터소프트웨어학부');
    await page.locator('input[placeholder="학번"]').fill('2023012345');
    await page.getByRole('button', { name: '다음' }).click();

    // Step 3: Paid Confirmation
    await expect(page.locator('text=회비를 납부하셨나요?')).toBeVisible();
    
    // Click the checkbox (which is the label wrapper)
    await page.locator('label').click();
    
    // Click submit
    await page.getByRole('button', { name: '다음' }).click();

    // Verify signup completion
    await expect(page.locator('text=회원가입이 완료되었습니다')).toBeVisible();

    // Take screenshot of signup complete
    await page.screenshot({ path: 'tests/e2e/screenshots/1_signup_done.png' });

    // 3. Switch to Login Modal
    await page.getByRole('button', { name: '로그인 하기' }).click();

    // Fill login credentials
    await page.locator('input[type="email"]').fill(testEmail);
    await page.locator('input[type="password"]').fill(testPassword);
    
    // Take screenshot of login modal
    await page.screenshot({ path: 'tests/e2e/screenshots/2_login_modal.png' });

    await page.getByRole('button', { name: '로그인', exact: true }).last().click();

    // 4. Verify homepage loaded (should redirect to /home)
    await page.waitForURL('**/home');
    await page.waitForTimeout(300);
    await page.screenshot({ path: 'tests/e2e/screenshots/3_home_page.png' });

    // 5. Check other navigation links
    // About greetings page
    await page.hover('text=About');
    const greetingLink = page.getByRole('link', { name: '인사말' });
    await expect(greetingLink).toBeVisible();
    await greetingLink.click();
    await expect(page).toHaveURL(/.*\/about\/greeting/);
    await page.screenshot({ path: 'tests/e2e/screenshots/4_greeting_page.png' });

    // 6. Test Free Board (Create new post)
    await page.hover('text=Board');
    const freeBoardLink = page.getByRole('link', { name: '자유 게시판' });
    await expect(freeBoardLink).toBeVisible();
    await freeBoardLink.click();
    await expect(page).toHaveURL(/.*\/board\/free/);
    await page.screenshot({ path: 'tests/e2e/screenshots/5_free_board.png' });

    // Click write new post
    const writeBtn = page.getByRole('button', { name: /새글작성/i });
    await expect(writeBtn).toBeVisible();
    await writeBtn.click();
    await expect(page).toHaveURL(/.*\/board\/free\/new/);

    // Fill post content
    const testTitle = `E2E Test Title - ${uniqueId}`;
    const testContent = `E2E Test Content - This post was automatically generated by Playwright test at ${new Date().toISOString()}.`;
    await page.locator('input[placeholder="제목을 입력하세요"]').fill(testTitle);
    await page.locator('textarea[placeholder="내용을 입력하세요"]').fill(testContent);
    await page.screenshot({ path: 'tests/e2e/screenshots/6_new_post.png' });
    await page.getByRole('button', { name: '등록하기' }).click();

    // Wait and verify post is in the list
    await page.waitForURL('**/board/free');
    await expect(page.locator(`text=${testTitle}`)).toBeVisible();
    await page.screenshot({ path: 'tests/e2e/screenshots/7_free_board_with_post.png' });

    // View detail
    await page.locator(`text=${testTitle}`).click();
    await expect(page.locator(`text=${testContent}`)).toBeVisible();
    await page.screenshot({ path: 'tests/e2e/screenshots/8_post_detail.png' });

    // 7. Check My Library (Books) page
    const myLibraryLink = page.getByRole('link', { name: '내 서재' });
    if (await myLibraryLink.count() > 0) {
      await myLibraryLink.click();
    } else {
      // Direct navigation if link not in header
      await page.goto('/books');
    }
    await expect(page).toHaveURL(/.*\/books/);
    await page.screenshot({ path: 'tests/e2e/screenshots/9_books_page.png' });

    console.log(`Console errors captured: ${consoleErrors.length}`);
    expect(consoleErrors.length).toBe(0);
  });
});
